server {
    listen 8080;
    root /usr/share/nginx/html;

    resolver [::1] valid=10s ipv6=on;

    location /api/ {
        set $upstream http://api.railway.internal:8080;
        proxy_pass $upstream;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}