// <auto-generated />
using GoGolf.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoGolf.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920124913_SeedClubData")]
    partial class SeedClubData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoGolf.Api.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FromPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Moregloed, Pretoria",
                            FromPrice = 150m,
                            Name = "Shank",
                            Rating = 5m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Montana, Pretoria",
                            FromPrice = 200m,
                            Name = "Simpact",
                            Rating = 5m
                        },
                        new
                        {
                            Id = 3,
                            Address = "Fourways, Johannesburg",
                            FromPrice = 185m,
                            Name = "Golf Bar",
                            Rating = 4.7m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
