// <auto-generated />
using GoGolf.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoGolf.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920154738_seedBays")]
    partial class seedBays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoGolf.Api.Models.Bay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "Name")
                        .IsUnique();

                    b.ToTable("Bays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            IsActive = true,
                            Name = "Bay 1"
                        },
                        new
                        {
                            Id = 2,
                            ClubId = 1,
                            IsActive = true,
                            Name = "Bay 2"
                        },
                        new
                        {
                            Id = 3,
                            ClubId = 1,
                            IsActive = true,
                            Name = "Bay 3"
                        },
                        new
                        {
                            Id = 4,
                            ClubId = 2,
                            IsActive = true,
                            Name = "Bay 1"
                        },
                        new
                        {
                            Id = 5,
                            ClubId = 2,
                            IsActive = true,
                            Name = "Bay 2"
                        },
                        new
                        {
                            Id = 6,
                            ClubId = 3,
                            IsActive = true,
                            Name = "Bay 1"
                        },
                        new
                        {
                            Id = 7,
                            ClubId = 3,
                            IsActive = true,
                            Name = "Bay 2"
                        },
                        new
                        {
                            Id = 8,
                            ClubId = 3,
                            IsActive = true,
                            Name = "Bay 3"
                        },
                        new
                        {
                            Id = 9,
                            ClubId = 3,
                            IsActive = true,
                            Name = "Bay 4"
                        },
                        new
                        {
                            Id = 10,
                            ClubId = 3,
                            IsActive = true,
                            Name = "Bay 5"
                        });
                });

            modelBuilder.Entity("GoGolf.Api.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("FromPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Moregloed, Pretoria",
                            FromPrice = 150m,
                            Name = "Shank",
                            Rating = 5m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Montana, Pretoria",
                            FromPrice = 200m,
                            Name = "Simpact",
                            Rating = 5m
                        },
                        new
                        {
                            Id = 3,
                            Address = "Fourways, Johannesburg",
                            FromPrice = 185m,
                            Name = "Golf Bar",
                            Rating = 4.7m
                        });
                });

            modelBuilder.Entity("GoGolf.Api.Models.Bay", b =>
                {
                    b.HasOne("GoGolf.Api.Models.Club", "Club")
                        .WithMany("Bays")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("GoGolf.Api.Models.Club", b =>
                {
                    b.Navigation("Bays");
                });
#pragma warning restore 612, 618
        }
    }
}
