// <auto-generated />
using GoGolf.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoGolf.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920152705_AddBays")]
    partial class AddBays
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoGolf.Api.Models.Bay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId", "Name")
                        .IsUnique();

                    b.ToTable("Bays");
                });

            modelBuilder.Entity("GoGolf.Api.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FromPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Moregloed, Pretoria",
                            FromPrice = 150m,
                            Name = "Shank",
                            Rating = 5m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Montana, Pretoria",
                            FromPrice = 200m,
                            Name = "Simpact",
                            Rating = 5m
                        },
                        new
                        {
                            Id = 3,
                            Address = "Fourways, Johannesburg",
                            FromPrice = 185m,
                            Name = "Golf Bar",
                            Rating = 4.7m
                        });
                });

            modelBuilder.Entity("GoGolf.Api.Models.Bay", b =>
                {
                    b.HasOne("GoGolf.Api.Models.Club", "Club")
                        .WithMany("Bays")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("GoGolf.Api.Models.Club", b =>
                {
                    b.Navigation("Bays");
                });
#pragma warning restore 612, 618
        }
    }
}
